import { useEffect, useState, type FormEvent } from 'react'
import { getPublicPoll, submitVote } from '../../entities/poll/api/publicPolls'
import type { Poll } from '../../entities/poll/model/types'

interface PollVotePageProps { pollId: string }
export function PollVotePage({ pollId }: PollVotePageProps) {
  const [poll, setPoll] = useState<Poll | null>(null); const [loadError, setLoadError] = useState<string | null>(null); const [isLoading, setIsLoading] = useState(true); const [selectedOptionIds, setSelectedOptionIds] = useState<string[]>([]); const [selectionError, setSelectionError] = useState<string | null>(null); const [submitError, setSubmitError] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const [isComplete, setIsComplete] = useState(false)
  useEffect(() => { let isCurrent = true; const loadPoll = async () => { setIsLoading(true); setLoadError(null); try { const publicPoll = await getPublicPoll(pollId); if (isCurrent) setPoll(publicPoll) } catch (error) { if (isCurrent) setLoadError(error instanceof Error ? error.message : 'Не удалось загрузить опрос.') } finally { if (isCurrent) setIsLoading(false) } }; void loadPoll(); return () => { isCurrent = false } }, [pollId])
  const selectOption = (optionId: string) => { if (!poll) return; setSelectionError(null); setSubmitError(null); if (poll.selection_type === 'single') { setSelectedOptionIds([optionId]); return }; setSelectedOptionIds((current) => { if (current.includes(optionId)) return current.filter((id) => id !== optionId); if (current.length >= poll.max_selections) { setSelectionError(`Можно выбрать не более ${poll.max_selections} вариантов.`); return current }; return [...current, optionId] }) }
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!poll) return; setSelectionError(null); setSubmitError(null); if (poll.selection_type === 'single' && selectedOptionIds.length !== 1) { setSelectionError('Выберите один вариант ответа.'); return }; if (poll.selection_type === 'multiple' && (selectedOptionIds.length < poll.min_selections || selectedOptionIds.length > poll.max_selections)) { setSelectionError(`Выберите от ${poll.min_selections} до ${poll.max_selections} вариантов ответа.`); return }; setIsSubmitting(true); try { await submitVote(poll.id, selectedOptionIds); setIsComplete(true) } catch (error) { setSubmitError(error instanceof Error ? error.message : 'Не удалось учесть голос.') } finally { setIsSubmitting(false) } }
  if (isLoading) return <main className="grid min-h-screen place-items-center p-6 text-neutral-500">Загрузка опроса…</main>
  if (loadError || !poll) return <main className="grid min-h-screen place-items-center bg-white p-6 text-center text-black"><section className="max-w-md border border-red-300 bg-red-50 p-6"><h1 className="text-xl font-semibold">Опрос недоступен</h1><p className="mt-2 text-red-800">{loadError || 'Опрос не найден.'}</p></section></main>
  if (isComplete) return <main className="grid min-h-screen place-items-center bg-white p-6 text-center text-black"><section className="max-w-md border-2 border-black p-8"><p aria-hidden="true" className="text-4xl">✓</p><h1 className="mt-4 text-2xl font-bold">Спасибо за голос!</h1><p className="mt-2 text-neutral-600">Ваш ответ успешно учтён.</p></section></main>
  const isMultiple = poll.selection_type === 'multiple'; const selectionHint = isMultiple ? `Выберите от ${poll.min_selections} до ${poll.max_selections} вариантов.` : 'Выберите один вариант.'
  return <main className="grid min-h-screen place-items-center bg-white p-4 text-black sm:p-8"><section className="w-full max-w-xl border-2 border-black p-6 sm:p-8"><p className="text-sm uppercase tracking-widest text-neutral-500">Голосование</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{poll.question}</h1><p className="mt-3 text-sm text-neutral-600">{selectionHint}</p><form className="mt-6 space-y-3" onSubmit={submit}><fieldset><legend className="sr-only">Варианты ответа</legend><div className="space-y-2">{poll.options.map((option) => { const isSelected = selectedOptionIds.includes(option.id); return <label className={`flex cursor-pointer items-center gap-3 border p-4 transition-colors ${isSelected ? 'border-black bg-neutral-100' : 'border-neutral-300 hover:border-black'}`} key={option.id}><input checked={isSelected} name="vote-option" onChange={() => selectOption(option.id)} type={isMultiple ? 'checkbox' : 'radio'} /><span>{option.text}</span></label> })}</div></fieldset>{selectionError && <p className="text-sm text-red-700">{selectionError}</p>}{submitError && <p className="border border-red-300 bg-red-50 p-3 text-sm text-red-700">{submitError}</p>}<button className="mt-3 w-full rounded bg-black px-5 py-3 font-medium text-white disabled:cursor-not-allowed disabled:opacity-50" disabled={isSubmitting} type="submit">{isSubmitting ? 'Отправка…' : 'Отправить голос'}</button></form></section></main>
}
