import { useEffect, useRef, useState } from 'react'
import type { Poll, PollResults } from '../../entities/poll/model/types'
import { HttpError } from '../../shared/api/http'
import { getPollResults, getPolls } from '../../features/admin-polls/api/adminPolls'
import { CreatePollModal } from '../../features/admin-polls/ui/CreatePollModal'
import { PollsList } from '../../features/admin-polls/ui/PollsList'
import { ResultsModal } from '../../features/admin-polls/ui/ResultsModal'

interface AdminPollsPageProps { onUnauthorized: () => void }
export function AdminPollsPage({ onUnauthorized }: AdminPollsPageProps) {
  const [polls, setPolls] = useState<Poll[]>([]); const [isLoading, setIsLoading] = useState(true); const [loadError, setLoadError] = useState<string | null>(null); const [isCreateOpen, setIsCreateOpen] = useState(false); const [selectedPoll, setSelectedPoll] = useState<Poll | null>(null); const [results, setResults] = useState<PollResults | null>(null); const [resultsError, setResultsError] = useState<string | null>(null); const [areResultsLoading, setAreResultsLoading] = useState(false); const [currentTime, setCurrentTime] = useState(Date.now()); const [copiedPollId, setCopiedPollId] = useState<string | null>(null); const resultsRequestId = useRef(0)
  const loadPolls = async () => { setIsLoading(true); setLoadError(null); try { setPolls(await getPolls()) } catch (error) { if (error instanceof HttpError && error.status === 401) { onUnauthorized(); return }; setLoadError(error instanceof Error ? error.message : 'Не удалось загрузить опросы.') } finally { setIsLoading(false) } }
  useEffect(() => { void loadPolls(); const timer = window.setInterval(() => setCurrentTime(Date.now()), 30_000); return () => window.clearInterval(timer) }, [])
  const openResults = async (poll: Poll) => { const requestId = ++resultsRequestId.current; setSelectedPoll(poll); setResults(null); setResultsError(null); setAreResultsLoading(true); try { const pollResults = await getPollResults(poll.id); if (resultsRequestId.current === requestId) setResults(pollResults) } catch (error) { if (error instanceof HttpError && error.status === 401) { onUnauthorized(); return }; if (resultsRequestId.current === requestId) setResultsError(error instanceof Error ? error.message : 'Не удалось загрузить статистику.') } finally { if (resultsRequestId.current === requestId) setAreResultsLoading(false) } }
  const closeResults = () => { resultsRequestId.current += 1; setSelectedPoll(null) }
  const copyPollId = async (pollId: string) => { try { await navigator.clipboard.writeText(pollId); setCopiedPollId(pollId); window.setTimeout(() => setCopiedPollId(null), 2_000) } catch { setCopiedPollId(null) } }
  return <main className="min-h-screen bg-white px-4 py-8 text-black sm:px-8"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-col gap-4 border-b-2 border-black pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm uppercase tracking-widest text-neutral-500">Панель администратора</p><h1 className="mt-1 text-3xl font-bold">Опросы</h1></div><div className="flex flex-wrap gap-2"><button className="rounded bg-black px-5 py-2.5 font-medium text-white hover:bg-neutral-800" onClick={() => setIsCreateOpen(true)} type="button">Создать опрос</button><button className="rounded border border-black px-5 py-2.5 font-medium hover:bg-neutral-100" onClick={onUnauthorized} type="button">Выйти</button></div></header>{isLoading && <p className="py-10 text-center text-neutral-500">Загрузка опросов…</p>}{loadError && <div className="flex items-center justify-between gap-4 border border-red-300 bg-red-50 p-4 text-red-800"><span>{loadError}</span><button className="shrink-0 underline" onClick={() => void loadPolls()} type="button">Повторить</button></div>}{!isLoading && !loadError && polls.length === 0 && <p className="border border-dashed border-neutral-400 px-4 py-12 text-center text-neutral-500">Опросов пока нет.</p>}{!loadError && polls.length > 0 && <PollsList copiedPollId={copiedPollId} currentTime={currentTime} onCopy={copyPollId} onOpenResults={openResults} polls={polls} />}</div>{isCreateOpen && <CreatePollModal onClose={() => setIsCreateOpen(false)} onCreated={(poll) => setPolls((current) => [poll, ...current])} onUnauthorized={onUnauthorized} />}{selectedPoll && <ResultsModal error={resultsError} isLoading={areResultsLoading} onClose={closeResults} poll={selectedPoll} results={results} />}</main>
}
